[package]
name = "rust_kv"
version = "0.1.0"
edition = "2024"

[lib]
name = "rust_kv"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
indexmap = "2"
